// svelte-frontend/src/components/CVList/Button/CVButtonDownload.svelte
<script>
      import { currentUser } from "../../../services/Store";
      import { URL_DOWNLOAD_CV } from "../../../utils/API";

      export let cv;
</script>

<a
      class="btn btn-success btn-sm"
      href={`${URL_DOWNLOAD_CV}/${$currentUser.id}/${cv.id}`}
      target="_blank"
      rel="noreferrer"
    >
      Télécharger
    </a>

<style>
    
</style>

// vue-frontend/src/components/CVList/Button/CVButtonDownload.vue
<template>
  <a
      class="btn btn-success btn-sm"
      :href="`${url}/${user.id}/${cv.id}`"
      target="_blank"
      rel="noreferrer"
    >
      Télécharger
    </a>
</template>

<script>
import { URL_DOWNLOAD_CV } from "../../../utils/API";
import auth from "../../../services/Auth"

export default {
  name: "CVButtonDownload",
  props: {
    cv: Object,
  },
  data() {
    return {
      user: auth.user,
      url: URL_DOWNLOAD_CV
    };
  }
};
</script>
