// svelte-frontend/src/components/CVList/Button/CVButtonDelete.svelte
<script>
    import CVModalConfirmDelete from "../Modal/CVModalConfirmDelete.svelte";

    export let cv;
    let isOpen = false;
</script>

<button
  class="btn btn-danger btn-sm"
  type="button"
  on:click={() => (isOpen = !isOpen)}
>
  Supprimer
</button>

<CVModalConfirmDelete {isOpen} {cv}/>

<style>
    
</style>

// vue-frontend/src/components/CVList/Button/CVButtonDelete.vue
<template>
  <button
  class="btn btn-danger btn-sm"
  type="button"
  :click="() => (isOpen = !isOpen)"
>
  Supprimer
</button>

<CVModalConfirmeDelete />
</template>

<script>
import CVModalConfirmeDelete from "../Modal/CVModalConfirmeDelete.vue";

export default {
  name: "CVButtonDownload",
  props: {
    cv: Object,
  },
  components: {
      CVModalConfirmeDelete
  },
  data() {
    return {
        isOpen: false
    };
  },
};
</script>
