// svelte-frontend/src/components/CVList/Button/CVButtonActive.svelte
<script>
    import CVModalConfirmActive from "../Modal/CVModalConfirmActive.svelte";

    export let cv;
    let isOpen = false;
</script>

<button
  class="btn btn-warning btn-sm"
  type="button"
  disabled={cv.isActive}
  on:click={() => (isOpen = !isOpen)}
>
  {cv.isActive ? "Déjà Actif" : "Mettre Actif"}
</button>

<CVModalConfirmActive {isOpen} {cv}/>

<style>
    
</style>

// vue-frontend/src/components/CVList/Button/CVButtonActive.vue
<template>
  <button class="btn btn-sm btn-warning" @click="showModal" :disabled="cv.isActive">
    {{cv.isActive ? "Déjà Actif" : "Mettre Actif"}}
  </button>
  <CVModalConfirmActive v-if="displayModal" @close-modal-event="hideModal" :cv="cv"/>

</template>

<script>
import CVModalConfirmActive from "../Modal/CVModalConfirmActive.vue"

export default {
  name: "CVButtonDownload",
  props: {
    cv: Object,
  },
  components: {
    CVModalConfirmActive
  },
  data() {
    return {
      displayModal: false,
    };
  },
  methods: {
    showModal() {
      this.displayModal = true;
    },
    hideModal() {
      this.displayModal = false;
    },
  },
};
</script>
