// svelte-frontend/src/components/StudentList/StudentItem.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import Icon from "svelte-awesome";
  import {
    faUserCircle,
    faLaptopCode,
    faLandmark,
    faStethoscope,
  } from "@fortawesome/free-solid-svg-icons";

  const dispatch = createEventDispatcher();

  export let student;

  let icon =
    student.department === "COMPUTER_SCIENCE"
      ? faLaptopCode
      : student.department === "ARCHITECTURE"
      ? faLandmark
      : student.department === "NURSING"
      ? faStethoscope
      : faUserCircle;
</script>

<div class="row list_node" on:click={() => dispatch('click', student)}>
  <div class="col-sm-3">
    <Icon data={icon} style="width:30%;height:30%" />
  </div>
  <div class="col-sm-9 list_node_text">
    {student.firstName}
    {student.lastName}
  </div>
</div>

<style>
  .list_node {
    background: rgba(255, 64, 88, 0.74);
    box-shadow: 0px 2px 20px 2px rgba(255, 114, 132, 0.5);
    border-radius: 8px;
    padding: 15px 30px;
    border: none;
    color: #fff;
    font-size: 14px;
    position: relative;
    cursor: pointer;
    margin-bottom: 25px;
    align-items: center;
  }

  .list_node_text {
    font-size: 2rem;
    list-style-type: none;
  }
</style>

// vue-frontend/src/components/StudentList/StudentItem.vue
<template>
  <div class="row list_node" @click="changeCurrentStudent">
    <div class="col-sm-3">
        <FontAwesomeIcon :icon="['fas', icon]" style="width: 30%; height: 30%" />
    </div>
    <div class="col-sm-9 list_node_text">
      {{ student.firstName }}
      {{ student.lastName }}
    </div>
  </div>
</template>

<script>
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

export default {
  name: "StudentItem",
  components: {
      FontAwesomeIcon
  },
  props: {
    student: Object,
  },
  data() {
    return {
      icon:
        this.student.department === "COMPUTER_SCIENCE"
      ? 'laptop-code'
      : this.student.department === "ARCHITECTURE"
      ? 'landmark'
      : this.student.department === "NURSING"
      ? 'stethoscope'
      : 'user-circle'
    }; 
  },
  methods: {
      changeCurrentStudent() {
          this.$emit('change-current-student', this.student)
      }
  }
};
</script>

<style>
.list_node {
  background: rgba(255, 64, 88, 0.74);
  box-shadow: 0px 2px 20px 2px rgba(255, 114, 132, 0.5);
  border-radius: 8px;
  padding: 15px 30px;
  border: none;
  color: #fff;
  font-size: 14px;
  position: relative;
  cursor: pointer;
  margin-bottom: 25px;
  align-items: center;
}

.list_node_text {
  font-size: 2rem;
  list-style-type: none;
}
</style>
