// svelte-frontend/src/components/CVList/CVItem.svelte
<script>
    import CVButtonDownload from "./Button/CVButtonDownload.svelte";
    import CVButtonDelete from "./Button/CVButtonDelete.svelte";
    import CVButtonActive from "./Button/CVButtonActive.svelte";
    export let cv;

    let document = cv.pdfdocument
</script>

<tr>
    <td>{document.name}</td>
    <td>
        <CVButtonDownload {cv}/>
    </td>
    <td>
        <CVButtonDelete {cv}/>
    </td>
    <td>
        <CVButtonActive {cv}/>
    </td>
    <td>ICON</td>
</tr>

<style>
    
</style>

// vue-frontend/src/components/CVList/CVItem.vue
<template>
    <tr>
  <td>{{document.name}}</td>
  <td>
    <CVButtonDownload />
  </td>
  <td>
    <CVButtonDelete />
  </td>
  <td>
    <CVButtonActive />
  </td>
  <td>
    ICON
  </td>
</tr>
</template>

<script>
import CVButtonDownload from "./Button/CVButtonDownload.vue";
  import CVButtonDelete from "./Button/CVButtonDelete.vue";
  import CVButtonActive from "./Button/CVButtonActive.vue";
  

export default {
  name: "CVItem",
  props: {
      cv: Object
  },
  components: {
    CVButtonDownload,
    CVButtonDelete,
    CVButtonActive
  },
  data() {
    return {
      document: this.cv.pdfdocument,
    };
  },
};
</script>

<style>

</style>
