// vue-frontend/src/components/StudentList/Modal/StudentModalValidCV.vue
<template>
  <div class="bootstrap-modal-no-jquery">
    <div class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">
              Voulez-vous confirmer le cv de {{ student.firstName }}
              {{ student.lastName }} ?
            </h5>
          </div>
          <div class="modal-body">
            <button
              type="button"
              class="btn btn-danger mx-3"
              @click="closeModal"
            >
              Non
            </button>
            <a
              class="btn btn-warning mx-3"
              :href="`${url_download}/${student.id}/${
                student.cvlist.filter((cv) => cv.isActive === true)[0].id
              }`"
              target="_blank"
              rel="noreferrer"
            >
              Télécharger
            </a>
            <button
              type="button"
              class="btn btn-success mx-3"
              @click="confirmValid"
            >
              Oui
            </button>
          </div>
          <div class="modal-footer">
            <div class="row">
              <div class="col-xs-12">
                <p
                  :style="
                    errorMessage.startsWith('Erreur')
                      ? 'color:red;'
                      : 'color:green;'
                  "
                >
                  {{ errorMessage }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { URL_DOWNLOAD_CV, URL_VALID_CV_ACTIVE } from "../../../utils/API";
  import axios from "axios"

export default {
  props: {
    student: Object,
  },
  data() {
    return {
      errorMessage: "",
      btnDisabled: false,
      url_download: URL_DOWNLOAD_CV,
    };
  },
  methods: {
    closeModal() {
      this.$emit("close-modal-event");
    },
    confirmValid() {
        console.log(`${URL_VALID_CV_ACTIVE}/${this.student.id}`)
      axios
      .post(`${URL_VALID_CV_ACTIVE}/${this.student.id}`)
      .then(() => {
        setTimeout(() => {
            this.errorMessage = ""
            this.$emit("valid-cv")
        }, 2000);
        this.errorMessage = "Confirmation de la validation";
      })
      .catch(() => {
        this.errorMessage = "Erreur durant la validation du CV";
      });
    },
  }
};
</script>

<style scoped>
/* Override default value of 'none' */
.modal {
  display: block;
  color: black;
  background-color: rgba(0, 0, 0, 0.55);
}

.modal-dialog {
  margin-top: 7%;
}
</style>

// svelte-frontend/src/components/StudentList/Modal/StudentModalValidCV.svelte
<script>
  import Modal from "sv-bootstrap-modal";
  import { URL_DOWNLOAD_CV } from "../../../utils/API";  
  import { createEventDispatcher } from 'svelte';
  import { URL_VALID_CV_ACTIVE } from "../../../utils/API";
  import axios from "axios"

  const dispatch = createEventDispatcher();

  export let isOpen;
  export let currentStudent;
  let errorMessage = "";
  let btnDisabled = false;

  function validCV() {
    axios
      .post(`${URL_VALID_CV_ACTIVE}/${currentStudent.id}`)
      .then((response) => {
        setTimeout(() => {
            errorMessage = ""
            dispatch("valid-cv")
        }, 2000);
        errorMessage = "Confirmation de la validation";
      })
      .catch((error) => {
        errorMessage = "Erreur durant la validation du CV";
      });
  }
</script>

<Modal bind:open={isOpen}>
  <div class="modal-header">
    <h5 class="modal-title" style="color:black;">
      Voulez-vous confirmer le cv de {currentStudent.firstName} {currentStudent.lastName} ?
    </h5>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-sm-3">
        <button
          type="button"
          class="btn btn-lg btn-success"
          on:click={validCV}
          disabled={btnDisabled}>Oui</button
        >
      </div>
      <div class="col-sm-6">
        <a
          class="btn btn-lg btn-warning"
          href={`${URL_DOWNLOAD_CV}/${currentStudent.id}/${
            currentStudent.cvlist.filter((cv) => cv.isActive === true)[0].id
          }`}
          target="_blank"
          rel="noreferrer"
        >
          Télécharger
        </a>
      </div>

      <div class="col-sm-3">
        <button
          type="button"
          class="btn btn-lg btn-danger"
          on:click={() => (isOpen = false)}>Non</button
        >
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <div class="row">
      <div class="col-xs-12">
        <p
          style={errorMessage.startsWith("Erreur")
            ? "color:red;"
            : "color:green;"}
        >
          {errorMessage}
        </p>
      </div>
    </div>
  </div>
</Modal>

<style>
</style>
