// vue-frontend/src/components/CVList/Modal/CVModalConfirmDelete.vue
<template>
  <div class="bootstrap-modal-no-jquery">
    <div class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Êtes-vous certain de supprimer ce CV ?</h5>
          </div>
          <div class="modal-body">
            <button
              type="button"
              class="btn btn-danger mx-3"
              @click="closeModal"
            >
              Non
            </button>
            <button
              type="button"
              class="btn btn-success mx-3"
              @click="confirmDelete"
            >
              Oui
            </button>
          </div>
          <div class="modal-footer">
            <div class="row">
              <div class="col-xs-12">
                <p
                  :style="
                    errorMessage.startsWith('Erreur')
                      ? 'color:red;'
                      : 'color:green;'
                  "
                >
                  {{ errorMessage }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import auth from "../../../services/Auth";
import { URL_DELETE_CV } from "../../../utils/API";

export default {
  props: {
    cv: Object,
  },
  data() {
    return {
      errorMessage: "",
      btnDisabled: false,
      currentUser: auth.user,
    };
  },
  methods: {
    closeModal() {
      this.$emit("close-modal-event");
    },
    confirmDelete() {
      axios
        .delete(`${URL_DELETE_CV}/${this.currentUser.id}/${this.cv.id}`)
        .then((response) => {
          this.errorMessage = "Confirmation de la suppression";
          this.btnDisabled = true;
          setTimeout(() => {
            auth.updateUser(response.data);
            this.closeModal();
          }, 2000);
        })
        .catch(() => {
          this.errorMessage = "Erreur lors de la suppression de CV...";
        });
    },
  },
};
</script>

<style scoped>
/* Override default value of 'none' */
.modal {
  display: block;
  color: black;
  background-color: rgba(0, 0, 0, 0.55);
}

.modal-dialog {
  margin-top: 7%;
}
</style>

// svelte-frontend/src/components/CVList/Modal/CVModalConfirmDelete.svelte
<script>
    import Modal from "sv-bootstrap-modal";
    import axios from "axios";
    import { currentUser } from "../../../services/Store";
    import auth from "../../../services/Auth";
    import { URL_DELETE_CV } from "../../../utils/API";
  
    export let isOpen;
    export let cv;
    let errorMessage = "";
    let btnDisabled = false;
  
    function deleteCV() {
        axios
        .delete(`${URL_DELETE_CV}/${$currentUser.id}/${cv.id}`)
        .then((response) => {
            errorMessage = "Confirmation de la suppression";
            btnDisabled = true;
            setTimeout(() => {
              isOpen = false;
              auth.updateUser(response.data);
            }, 2000);
          })
          .catch((error) => {
            errorMessage = "Erreur lors de la suppression de CV...";
          });
      }
  </script>
  
  <Modal bind:open={isOpen}>
    <div class="modal-header">
      <h5 class="modal-title" style="color:black;">Êtes-vous certain de supprimer ce fichier?</h5>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col">
            <button
            type="button"
            class="btn btn-danger"
            on:click={() => (isOpen = false)}>Non</button
          >
          <button
            type="button"
            class="btn btn-success"
            on:click={deleteCV}
            disabled={btnDisabled}>Oui</button
          >
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <div class="row">
        <div class="col-xs-12">
          <p
            style={errorMessage.startsWith("Erreur")
              ? "color:red;"
              : "color:green;"}
          >
            {errorMessage}
          </p>
        </div>
      </div>
    </div>
  </Modal>
  
  <style>

  </style>
